// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5RnyjCbbCMeBTg3X-ucdPtlyI1XCrHQ',
    appId: '1:641736791998:web:23c852d16326c9347b8bef',
    messagingSenderId: '641736791998',
    projectId: 'instax-b581d',
    authDomain: 'instax-b581d.firebaseapp.com',
    storageBucket: 'instax-b581d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40Aa5YKqoUItBnPhdgKxxU3kqDXja9vE',
    appId: '1:641736791998:android:2072130f1c4ffae77b8bef',
    messagingSenderId: '641736791998',
    projectId: 'instax-b581d',
    storageBucket: 'instax-b581d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAbZikrPEcIj3aKx68L4eVdeQK2LeJD8',
    appId: '1:641736791998:ios:80c38ba5e7c8a3227b8bef',
    messagingSenderId: '641736791998',
    projectId: 'instax-b581d',
    storageBucket: 'instax-b581d.appspot.com',
    iosBundleId: 'com.example.instax',
  );
}
